### ISSUE TITLE
Laravel 6 Support

### ISSUE THREAD

**Issue by liran-co** [darkin1/intercom#17]
Would it be possible to get support for Laravel 6?

**Comment by trevorgehman** [comment]
Any reason this was closed? I'm curious whether Laravel 6 will be supported. @darkin1

**Comment by liran-co** [comment]
@trevorgehman Here's an alternative I wrote with Laravel 6 support: https://github.com/liran-co/laravel-intercom.

**Comment by darkin1** [comment]
Sorry for delay. I have added support for Laravel 6.x tagged by v2.0.1
