### ISSUE TITLE
Update version of Intercom PHP Client

### ISSUE THREAD

**Issue by gpassarelli** [darkin1/intercom#3]
Hey @darkin1, I've made a fork of your project, awesome by the way. But I would like to know if you plan to update to the new version of the Intercom PHP client. I've done this already, but it will brake if the users don't update their code, so I would like to know if you are interested into merge this fork or can I release as a new package?

Thanks

**Comment by darkin1** [comment]
Hi @gpassarelli I'll be more than happy if you want to be a part of this project. Of course you can send me your changes and I'll merge it ;)
