### ISSUE TITLE
Example in README

### ISSUE THREAD

**Issue by KrisBraun** [darkin1/intercom#5]
Could a usage example be added to `README.txt`? Reading the code, I've tried `\intercom` and `\Intercom` as dependancy injection parameters, but both have given `Class does not exist` errors.

**Comment by kyranb** [comment]
I'm having issues as well. After registering the wrapper, the following work:

`Intercom::client();` gives`PHP Fatal error:  Class 'Intercom' not found`

**Comment by kyranb** [comment]
Added an example here: #6

**Comment by darkin1** [comment]
close #6
